# -*- coding: utf-8 -*-
"""content-based-image-retrieval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K_DtX9l8GHOA4to6yabNJYuwZPsMA3Mz
"""

# 1. Gerekli kütüphaneleri içe aktarma
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
from PIL import Image
from tqdm import tqdm
import os

# 2. VGG16 modelini yükleme (sadece özellik çıkarımı için üst katmanlar hariç)
temel_model = VGG16(weights='imagenet', include_top=False, pooling='avg')
model = Model(inputs=temel_model.input, outputs=temel_model.output)

# 3. Görsel ön işleme fonksiyonu
def resmi_on_isle(resim_yolu):
    img = image.load_img(resim_yolu, target_size=(224, 224))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    return x

# 4. Google Colab üzerinden örnek görselleri yükleme
from google.colab import files
print("Veri seti için görselleri yükleyin:")
yuklenenler = files.upload() # 5-10 adet JPEG veya PNG sanat eseri resmi yükleyin
resim_yollari = list(yuklenenler.keys())

# 5. Yüklenen görsellerden yerleştirmeleri (embeddings) oluşturma
yerlestirmeler = []
for yol in tqdm(resim_yollari):
    img = resmi_on_isle(yol)
    ozellikler = model.predict(img)
    yerlestirmeler.append(ozellikler.flatten())

yerlestirmeler = np.array(yerlestirmeler)

# 6. PCA (Temel Bileşen Analizi) ile boyut indirgeme ve görselleştirme
pca = PCA(n_components=2)
pca_sonucu = pca.fit_transform(yerlestirmeler)

plt.figure(figsize=(10, 6))
sns.scatterplot(x=pca_sonucu[:, 0], y=pca_sonucu[:, 1])

for i, yol in enumerate(resim_yollari):
    plt.annotate(f"{i}", (pca_sonucu[i, 0], pca_sonucu[i, 1]))

plt.title("Sanat Eseri Resimlerinin PCA İzdüşümü")
plt.xlabel("Temel Bileşen 1")
plt.ylabel("Temel Bileşen 2")
plt.show()

# 7. t-SNE ile boyut indirgeme ve kümeleri görselleştirme
tsne = TSNE(n_components=2, perplexity=3, n_iter=1000, random_state=42) # perplexity 5'ten küçük olmalı, örneğin 3 olarak ayarlandı
tsne_sonucu = tsne.fit_transform(yerlestirmeler)

plt.figure(figsize=(10, 6))
sns.scatterplot(x=tsne_sonucu[:, 0], y=tsne_sonucu[:, 1])

for i, yol in enumerate(resim_yollari):
    plt.annotate(f"{i}", (tsne_sonucu[i, 0], tsne_sonucu[i, 1]))

plt.title("Sanat Eseri Resimlerinin t-SNE İzdüşümü")
plt.xlabel("Bileşen 1")
plt.ylabel("Bileşen 2")
plt.show()

# 8. Benzerlik araması için bir test (sorgu) resmi yükleme
print("Benzerlerini aramak istediğiniz sorgu resmini yükleyin:")
yuklenen_test = files.upload()
test_yolu = list(yuklenen_test.keys())[0]
test_resmi = resmi_on_isle(test_yolu)
test_yerlestirmesi = model.predict(test_resmi).flatten()

# 9. Kosinüs Benzerliği ile en yakın görseli bulma
from sklearn.metrics.pairwise import cosine_similarity
benzerlikler = cosine_similarity([test_yerlestirmesi], yerlestirmeler)[0]
en_yakin_indeks = np.argmax(benzerlikler)
print(f"Yüklenen resim şuna en çok benzemektedir: {resim_yollari[en_yakin_indeks]}")

# 10. Sorgu resmi ile bulunan en benzer resmi yan yana gösterme
fig, eksenler = plt.subplots(1, 2, figsize=(10, 5))

eksenler[0].imshow(Image.open(test_yolu))
eksenler[0].set_title("Sorgu Resmi")
eksenler[0].axis("off")

eksenler[1].imshow(Image.open(resim_yollari[en_yakin_indeks]))
eksenler[1].set_title(f"Eşleşen Resim\n({resim_yollari[en_yakin_indeks]})")
eksenler[1].axis("off")

plt.show()